# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'ToDoList' do
  #pod	'MaterialComponents'
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'GoogleSignIn', :inhibit_warnings => true
  pod 'FBSDKLoginKit', '4.42.0', :inhibit_warnings => true
  pod 'FBSDKCoreKit', '4.42.0'
  pod 'FacebookCore', '0.5.0'
  pod 'FacebookLogin', '0.5.0'
  #pod 'FacebookShare'
end
